ALTER TABLE region
ADD PRIMARY KEY (R_REGIONKEY);

ALTER TABLE nation
ADD PRIMARY KEY (N_NATIONKEY);

ALTER TABLE part
ADD PRIMARY KEY (P_PARTKEY);

ALTER TABLE supplier
ADD PRIMARY KEY (S_SUPPKEY);

ALTER TABLE partsupp
ADD PRIMARY KEY (PS_PARTKEY,PS_SUPPKEY);

ALTER TABLE customer
ADD PRIMARY KEY (C_CUSTKEY);

ALTER TABLE orders
ADD PRIMARY KEY (O_ORDERKEY);

ALTER TABLE lineitem
ADD PRIMARY KEY (L_ORDERKEY,L_LINENUMBER);
