CREATE INDEX IDX_SUPPLIER_NATION_KEY ON supplier (S_NATIONKEY);

CREATE INDEX IDX_PARTSUPP_PARTKEY ON partsupp (PS_PARTKEY);
CREATE INDEX IDX_PARTSUPP_SUPPKEY ON partsupp (PS_SUPPKEY);

CREATE INDEX IDX_CUSTOMER_NATIONKEY ON customer (C_NATIONKEY);

CREATE INDEX IDX_ORDERS_CUSTKEY ON orders (O_CUSTKEY);

CREATE INDEX IDX_LINEITEM_ORDERKEY ON lineitem (L_ORDERKEY);
CREATE INDEX IDX_LINEITEM_PART_SUPP ON lineitem (L_PARTKEY,L_SUPPKEY);

CREATE INDEX IDX_NATION_REGIONKEY ON nation (N_REGIONKEY);

CREATE INDEX IDX_LINEITEM_SHIPDATE ON lineitem (L_SHIPDATE, L_DISCOUNT, L_QUANTITY);

CREATE INDEX IDX_ORDERS_ORDERDATE ON orders (O_ORDERDATE);
